//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OESUI.UserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/VerifyUserLogin", ReplyAction="http://tempuri.org/IUserService/VerifyUserLoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OESLogic.ServiceException), Action="http://tempuri.org/IUserService/VerifyUserLoginServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/OESLogic")]
        [System.ServiceModel.FaultContractAttribute(typeof(OESException.DBException), Action="http://tempuri.org/IUserService/VerifyUserLoginDBExceptionFault", Name="DBException", Namespace="http://schemas.datacontract.org/2004/07/OESException")]
        OESModel.User VerifyUserLogin(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserByName", ReplyAction="http://tempuri.org/IUserService/GetUserByNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OESException.DBException), Action="http://tempuri.org/IUserService/GetUserByNameDBExceptionFault", Name="DBException", Namespace="http://schemas.datacontract.org/2004/07/OESException")]
        OESModel.User GetUserByName(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ModifyPassword", ReplyAction="http://tempuri.org/IUserService/ModifyPasswordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OESException.DBException), Action="http://tempuri.org/IUserService/ModifyPasswordDBExceptionFault", Name="DBException", Namespace="http://schemas.datacontract.org/2004/07/OESException")]
        void ModifyPassword(int userId, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : OESUI.UserService.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<OESUI.UserService.IUserService>, OESUI.UserService.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OESModel.User VerifyUserLogin(string userName, string password) {
            return base.Channel.VerifyUserLogin(userName, password);
        }
        
        public OESModel.User GetUserByName(string userName) {
            return base.Channel.GetUserByName(userName);
        }
        
        public void ModifyPassword(int userId, string password) {
            base.Channel.ModifyPassword(userId, password);
        }
    }
}
