//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoginUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap bg_data_header {
            get {
                object obj = ResourceManager.GetObject("bg_data_header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BTN_Close_16x16_png {
            get {
                object obj = ResourceManager.GetObject("BTN_Close_16x16.png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BTN_PageLeft_20x15_png {
            get {
                object obj = ResourceManager.GetObject("BTN_PageLeft_20x15.png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BTN_PageRight_20x15_png_ {
            get {
                object obj = ResourceManager.GetObject("BTN_PageRight_20x15.png ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Client_Login_Wrong_20X20 {
            get {
                object obj = ResourceManager.GetObject("ICN_Client_Login_Wrong_20X20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Client_PersonalInformation_20x20 {
            get {
                object obj = ResourceManager.GetObject("ICN_Client_PersonalInformation_20x20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Client_PersonalInformation_20x201 {
            get {
                object obj = ResourceManager.GetObject("ICN_Client_PersonalInformation_20x201", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Decrese_10x15_png {
            get {
                object obj = ResourceManager.GetObject("ICN_Decrese_10x15.png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Increase_10x15_png {
            get {
                object obj = ResourceManager.GetObject("ICN_Increase_10x15.png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Increase_10x151 {
            get {
                object obj = ResourceManager.GetObject("ICN_Increase_10x151", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Password_20x15_png {
            get {
                object obj = ResourceManager.GetObject("ICN_Password_20x15.png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Usename_20x20_png {
            get {
                object obj = ResourceManager.GetObject("ICN_Usename_20x20.png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ICN_Wrong_15x15 {
            get {
                object obj = ResourceManager.GetObject("ICN_Wrong_15x15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LOGO_Client_Login_40X300 {
            get {
                object obj = ResourceManager.GetObject("LOGO_Client_Login_40X300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LOGO_Client_Maxmize2 {
            get {
                object obj = ResourceManager.GetObject("LOGO_Client_Maxmize2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LOGO_Client_Minimize {
            get {
                object obj = ResourceManager.GetObject("LOGO_Client_Minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LOGO_Client_Titel_120x20 {
            get {
                object obj = ResourceManager.GetObject("LOGO_Client_Titel_120x20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LOGO_Client_Titel_120x201 {
            get {
                object obj = ResourceManager.GetObject("LOGO_Client_Titel_120x201", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LOGO_Client_Titel_120x202 {
            get {
                object obj = ResourceManager.GetObject("LOGO_Client_Titel_120x202", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LOGO_Client_TS_Close {
            get {
                object obj = ResourceManager.GetObject("LOGO_Client_TS_Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap myPic_close_win {
            get {
                object obj = ResourceManager.GetObject("myPic_close_win", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap myPic_title {
            get {
                object obj = ResourceManager.GetObject("myPic_title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap myPic_title1 {
            get {
                object obj = ResourceManager.GetObject("myPic_title1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap myPic_title2 {
            get {
                object obj = ResourceManager.GetObject("myPic_title2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pic_down_select {
            get {
                object obj = ResourceManager.GetObject("pic_down_select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pic_down_select1 {
            get {
                object obj = ResourceManager.GetObject("pic_down_select1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
