//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginUI.ExamService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="localhost:8888/OESLogic", ConfigurationName="ExamService.IExamService")]
    public interface IExamService {
        
        [System.ServiceModel.OperationContractAttribute(Action="localhost:8888/OESLogic/IExamService/FindAllExam", ReplyAction="localhost:8888/OESLogic/IExamService/FindAllExamResponse")]
        System.Collections.Generic.List<OESModel.Exam> FindAllExam(OESModel.Pagination pagination, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="localhost:8888/OESLogic/IExamService/SaveExamAnswer", ReplyAction="localhost:8888/OESLogic/IExamService/SaveExamAnswerResponse")]
        void SaveExamAnswer(int userId, int examId, int questionId, int answer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExamServiceChannel : LoginUI.ExamService.IExamService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExamServiceClient : System.ServiceModel.ClientBase<LoginUI.ExamService.IExamService>, LoginUI.ExamService.IExamService {
        
        public ExamServiceClient() {
        }
        
        public ExamServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExamServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExamServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExamServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<OESModel.Exam> FindAllExam(OESModel.Pagination pagination, int userId) {
            return base.Channel.FindAllExam(pagination, userId);
        }
        
        public void SaveExamAnswer(int userId, int examId, int questionId, int answer) {
            base.Channel.SaveExamAnswer(userId, examId, questionId, answer);
        }
    }
}
